# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frm_popup_M_Pay_Invc.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_popup_M_Pay_Invc(object):
    def setupUi(self, popup_M_Pay_Invc):
        popup_M_Pay_Invc.setObjectName("popup_M_Pay_Invc")
        popup_M_Pay_Invc.resize(1193, 484)
        self.centralwidget = QtWidgets.QWidget(popup_M_Pay_Invc)
        self.centralwidget.setObjectName("centralwidget")
        self.pbtn_Cancel = QtWidgets.QPushButton(self.centralwidget)
        self.pbtn_Cancel.setGeometry(QtCore.QRect(530, 390, 93, 28))
        self.pbtn_Cancel.setObjectName("pbtn_Cancel")
        self.pbtn_Save = QtWidgets.QPushButton(self.centralwidget)
        self.pbtn_Save.setGeometry(QtCore.QRect(400, 390, 93, 28))
        self.pbtn_Save.setObjectName("pbtn_Save")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 1161, 351))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        popup_M_Pay_Invc.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(popup_M_Pay_Invc)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1193, 26))
        self.menubar.setObjectName("menubar")
        popup_M_Pay_Invc.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(popup_M_Pay_Invc)
        self.statusbar.setObjectName("statusbar")
        popup_M_Pay_Invc.setStatusBar(self.statusbar)

        self.retranslateUi(popup_M_Pay_Invc)
        QtCore.QMetaObject.connectSlotsByName(popup_M_Pay_Invc)

    def retranslateUi(self, popup_M_Pay_Invc):
        _translate = QtCore.QCoreApplication.translate
        popup_M_Pay_Invc.setWindowTitle(_translate("popup_M_Pay_Invc", "关联支款单"))
        self.pbtn_Cancel.setText(_translate("popup_M_Pay_Invc", "取消"))
        self.pbtn_Save.setText(_translate("popup_M_Pay_Invc", "关联"))
