# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frm_popup_Purchase_Job_Order.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_popup_Purchase_Job_Order(object):
    def setupUi(self, popup_Purchase_Job_Order):
        popup_Purchase_Job_Order.setObjectName("popup_Purchase_Job_Order")
        popup_Purchase_Job_Order.resize(922, 393)
        self.centralwidget = QtWidgets.QWidget(popup_Purchase_Job_Order)
        self.centralwidget.setObjectName("centralwidget")
        self.pbtn_Update = QtWidgets.QPushButton(self.centralwidget)
        self.pbtn_Update.setGeometry(QtCore.QRect(720, 0, 88, 23))
        self.pbtn_Update.setObjectName("pbtn_Update")
        self.pbtn_Delete = QtWidgets.QPushButton(self.centralwidget)
        self.pbtn_Delete.setGeometry(QtCore.QRect(810, 0, 88, 23))
        self.pbtn_Delete.setObjectName("pbtn_Delete")
        self.pbtn_Cancel = QtWidgets.QPushButton(self.centralwidget)
        self.pbtn_Cancel.setGeometry(QtCore.QRect(540, 0, 88, 23))
        self.pbtn_Cancel.setObjectName("pbtn_Cancel")
        self.pbtn_Run = QtWidgets.QPushButton(self.centralwidget)
        self.pbtn_Run.setGeometry(QtCore.QRect(450, 0, 88, 23))
        self.pbtn_Run.setObjectName("pbtn_Run")
        self.pbtn_Modify = QtWidgets.QPushButton(self.centralwidget)
        self.pbtn_Modify.setGeometry(QtCore.QRect(630, 0, 88, 23))
        self.pbtn_Modify.setObjectName("pbtn_Modify")
        self.pbtn_New = QtWidgets.QPushButton(self.centralwidget)
        self.pbtn_New.setGeometry(QtCore.QRect(180, 0, 88, 23))
        self.pbtn_New.setObjectName("pbtn_New")
        self.pbtn_Save = QtWidgets.QPushButton(self.centralwidget)
        self.pbtn_Save.setGeometry(QtCore.QRect(270, 0, 88, 23))
        self.pbtn_Save.setObjectName("pbtn_Save")
        self.pbtn_Query = QtWidgets.QPushButton(self.centralwidget)
        self.pbtn_Query.setGeometry(QtCore.QRect(360, 0, 88, 23))
        self.pbtn_Query.setObjectName("pbtn_Query")
        self.pbtn_Pick = QtWidgets.QPushButton(self.centralwidget)
        self.pbtn_Pick.setGeometry(QtCore.QRect(710, 320, 88, 23))
        self.pbtn_Pick.setObjectName("pbtn_Pick")
        self.pbtn_Quit = QtWidgets.QPushButton(self.centralwidget)
        self.pbtn_Quit.setGeometry(QtCore.QRect(810, 320, 88, 23))
        self.pbtn_Quit.setObjectName("pbtn_Quit")
        self.lEdit_Name = QtWidgets.QLineEdit(self.centralwidget)
        self.lEdit_Name.setGeometry(QtCore.QRect(130, 100, 113, 20))
        self.lEdit_Name.setObjectName("lEdit_Name")
        self.lEdit_Pjt = QtWidgets.QLineEdit(self.centralwidget)
        self.lEdit_Pjt.setGeometry(QtCore.QRect(130, 160, 113, 20))
        self.lEdit_Pjt.setObjectName("lEdit_Pjt")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 100, 54, 12))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 160, 54, 12))
        self.label_2.setObjectName("label_2")
        self.pbtn_Popup = QtWidgets.QPushButton(self.centralwidget)
        self.pbtn_Popup.setGeometry(QtCore.QRect(250, 160, 21, 21))
        self.pbtn_Popup.setObjectName("pbtn_Popup")
        popup_Purchase_Job_Order.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(popup_Purchase_Job_Order)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 922, 23))
        self.menubar.setObjectName("menubar")
        popup_Purchase_Job_Order.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(popup_Purchase_Job_Order)
        self.statusbar.setObjectName("statusbar")
        popup_Purchase_Job_Order.setStatusBar(self.statusbar)

        self.retranslateUi(popup_Purchase_Job_Order)
        QtCore.QMetaObject.connectSlotsByName(popup_Purchase_Job_Order)

    def retranslateUi(self, popup_Purchase_Job_Order):
        _translate = QtCore.QCoreApplication.translate
        popup_Purchase_Job_Order.setWindowTitle(_translate("popup_Purchase_Job_Order", "MainWindow"))
        self.pbtn_Update.setText(_translate("popup_Purchase_Job_Order", "更新"))
        self.pbtn_Delete.setText(_translate("popup_Purchase_Job_Order", "删除"))
        self.pbtn_Cancel.setText(_translate("popup_Purchase_Job_Order", "取消"))
        self.pbtn_Run.setText(_translate("popup_Purchase_Job_Order", "执行"))
        self.pbtn_Modify.setText(_translate("popup_Purchase_Job_Order", "修改"))
        self.pbtn_New.setText(_translate("popup_Purchase_Job_Order", "新建"))
        self.pbtn_Save.setText(_translate("popup_Purchase_Job_Order", "保存"))
        self.pbtn_Query.setText(_translate("popup_Purchase_Job_Order", "查询"))
        self.pbtn_Pick.setText(_translate("popup_Purchase_Job_Order", "选择"))
        self.pbtn_Quit.setText(_translate("popup_Purchase_Job_Order", "退出"))
        self.label.setText(_translate("popup_Purchase_Job_Order", "订单名称"))
        self.label_2.setText(_translate("popup_Purchase_Job_Order", "所属项目"))
        self.pbtn_Popup.setText(_translate("popup_Purchase_Job_Order", "☺"))
