# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frm_popup_PurchaseList_Pre.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frm_popup_PurchaseList_Pre(object):
    def setupUi(self, frm_popup_PurchaseList_Pre):
        frm_popup_PurchaseList_Pre.setObjectName("frm_popup_PurchaseList_Pre")
        frm_popup_PurchaseList_Pre.resize(1026, 402)
        self.centralwidget = QtWidgets.QWidget(frm_popup_PurchaseList_Pre)
        self.centralwidget.setObjectName("centralwidget")
        self.le_popup_PurchaseList_Name = QtWidgets.QLineEdit(self.centralwidget)
        self.le_popup_PurchaseList_Name.setGeometry(QtCore.QRect(170, 90, 113, 21))
        self.le_popup_PurchaseList_Name.setObjectName("le_popup_PurchaseList_Name")
        self.lb_popup_PurchaseList_Pre_Name = QtWidgets.QLabel(self.centralwidget)
        self.lb_popup_PurchaseList_Pre_Name.setGeometry(QtCore.QRect(50, 90, 72, 15))
        self.lb_popup_PurchaseList_Pre_Name.setObjectName("lb_popup_PurchaseList_Pre_Name")
        self.le_popup_PurchaseList_Status = QtWidgets.QLineEdit(self.centralwidget)
        self.le_popup_PurchaseList_Status.setGeometry(QtCore.QRect(440, 90, 113, 21))
        self.le_popup_PurchaseList_Status.setObjectName("le_popup_PurchaseList_Status")
        self.lb_popup_PurchaseList_Status = QtWidgets.QLabel(self.centralwidget)
        self.lb_popup_PurchaseList_Status.setGeometry(QtCore.QRect(320, 90, 72, 15))
        self.lb_popup_PurchaseList_Status.setObjectName("lb_popup_PurchaseList_Status")
        self.lb_popup_PurchaseList_Commiter = QtWidgets.QLabel(self.centralwidget)
        self.lb_popup_PurchaseList_Commiter.setGeometry(QtCore.QRect(50, 230, 72, 15))
        self.lb_popup_PurchaseList_Commiter.setObjectName("lb_popup_PurchaseList_Commiter")
        self.lb_popup_PurchaseList_Approver = QtWidgets.QLabel(self.centralwidget)
        self.lb_popup_PurchaseList_Approver.setGeometry(QtCore.QRect(320, 230, 72, 15))
        self.lb_popup_PurchaseList_Approver.setObjectName("lb_popup_PurchaseList_Approver")
        self.le_popup_PurchaseList_Commiter = QtWidgets.QLineEdit(self.centralwidget)
        self.le_popup_PurchaseList_Commiter.setGeometry(QtCore.QRect(170, 230, 113, 21))
        self.le_popup_PurchaseList_Commiter.setObjectName("le_popup_PurchaseList_Commiter")
        self.le_popup_PurchaseList_Approver = QtWidgets.QLineEdit(self.centralwidget)
        self.le_popup_PurchaseList_Approver.setGeometry(QtCore.QRect(440, 230, 113, 21))
        self.le_popup_PurchaseList_Approver.setObjectName("le_popup_PurchaseList_Approver")
        self.pbtn_popup_PurchaseList_Pre_Save = QtWidgets.QPushButton(self.centralwidget)
        self.pbtn_popup_PurchaseList_Pre_Save.setGeometry(QtCore.QRect(630, 280, 93, 28))
        self.pbtn_popup_PurchaseList_Pre_Save.setObjectName("pbtn_popup_PurchaseList_Pre_Save")
        self.pbtn_popup_PurchaseList_Pre_Cancel = QtWidgets.QPushButton(self.centralwidget)
        self.pbtn_popup_PurchaseList_Pre_Cancel.setGeometry(QtCore.QRect(800, 280, 93, 28))
        self.pbtn_popup_PurchaseList_Pre_Cancel.setObjectName("pbtn_popup_PurchaseList_Pre_Cancel")
        frm_popup_PurchaseList_Pre.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(frm_popup_PurchaseList_Pre)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1026, 26))
        self.menubar.setObjectName("menubar")
        frm_popup_PurchaseList_Pre.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(frm_popup_PurchaseList_Pre)
        self.statusbar.setObjectName("statusbar")
        frm_popup_PurchaseList_Pre.setStatusBar(self.statusbar)

        self.retranslateUi(frm_popup_PurchaseList_Pre)
        QtCore.QMetaObject.connectSlotsByName(frm_popup_PurchaseList_Pre)

    def retranslateUi(self, frm_popup_PurchaseList_Pre):
        _translate = QtCore.QCoreApplication.translate
        frm_popup_PurchaseList_Pre.setWindowTitle(_translate("frm_popup_PurchaseList_Pre", "采购项"))
        self.lb_popup_PurchaseList_Pre_Name.setText(_translate("frm_popup_PurchaseList_Pre", "模块名称"))
        self.lb_popup_PurchaseList_Status.setText(_translate("frm_popup_PurchaseList_Pre", "状态"))
        self.lb_popup_PurchaseList_Commiter.setText(_translate("frm_popup_PurchaseList_Pre", "提交人"))
        self.lb_popup_PurchaseList_Approver.setText(_translate("frm_popup_PurchaseList_Pre", "审核人"))
        self.pbtn_popup_PurchaseList_Pre_Save.setText(_translate("frm_popup_PurchaseList_Pre", "保存"))
        self.pbtn_popup_PurchaseList_Pre_Cancel.setText(_translate("frm_popup_PurchaseList_Pre", "取消"))
