# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frm_popup_Payment.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_popup_Payment(object):
    def setupUi(self, popup_Payment):
        popup_Payment.setObjectName("popup_Payment")
        popup_Payment.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(popup_Payment)
        self.centralwidget.setObjectName("centralwidget")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(150, 40, 110, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.lb_date = QtWidgets.QLabel(self.centralwidget)
        self.lb_date.setGeometry(QtCore.QRect(40, 40, 72, 15))
        self.lb_date.setObjectName("lb_date")
        self.le_amount = QtWidgets.QLineEdit(self.centralwidget)
        self.le_amount.setGeometry(QtCore.QRect(150, 100, 113, 21))
        self.le_amount.setObjectName("le_amount")
        self.lb_amount = QtWidgets.QLabel(self.centralwidget)
        self.lb_amount.setGeometry(QtCore.QRect(40, 100, 111, 16))
        self.lb_amount.setObjectName("lb_amount")
        self.lb_department = QtWidgets.QLabel(self.centralwidget)
        self.lb_department.setGeometry(QtCore.QRect(40, 160, 72, 15))
        self.lb_department.setObjectName("lb_department")
        self.lb_employee = QtWidgets.QLabel(self.centralwidget)
        self.lb_employee.setGeometry(QtCore.QRect(40, 210, 72, 15))
        self.lb_employee.setObjectName("lb_employee")
        self.lb_note_no = QtWidgets.QLabel(self.centralwidget)
        self.lb_note_no.setGeometry(QtCore.QRect(40, 310, 72, 15))
        self.lb_note_no.setObjectName("lb_note_no")
        self.lb_reason = QtWidgets.QLabel(self.centralwidget)
        self.lb_reason.setGeometry(QtCore.QRect(50, 360, 72, 15))
        self.lb_reason.setObjectName("lb_reason")
        self.lb_type = QtWidgets.QLabel(self.centralwidget)
        self.lb_type.setGeometry(QtCore.QRect(40, 260, 72, 15))
        self.lb_type.setObjectName("lb_type")
        self.le_department = QtWidgets.QLineEdit(self.centralwidget)
        self.le_department.setGeometry(QtCore.QRect(150, 160, 113, 21))
        self.le_department.setObjectName("le_department")
        self.le_employee = QtWidgets.QLineEdit(self.centralwidget)
        self.le_employee.setGeometry(QtCore.QRect(150, 210, 113, 21))
        self.le_employee.setObjectName("le_employee")
        self.le_type = QtWidgets.QLineEdit(self.centralwidget)
        self.le_type.setGeometry(QtCore.QRect(150, 260, 113, 21))
        self.le_type.setObjectName("le_type")
        self.le_note_no = QtWidgets.QLineEdit(self.centralwidget)
        self.le_note_no.setGeometry(QtCore.QRect(150, 310, 113, 21))
        self.le_note_no.setObjectName("le_note_no")
        self.le_reason = QtWidgets.QLineEdit(self.centralwidget)
        self.le_reason.setGeometry(QtCore.QRect(150, 360, 111, 21))
        self.le_reason.setObjectName("le_reason")
        self.pbtn_Save = QtWidgets.QPushButton(self.centralwidget)
        self.pbtn_Save.setGeometry(QtCore.QRect(400, 390, 93, 28))
        self.pbtn_Save.setObjectName("pbtn_Save")
        self.pbtn_Cancel = QtWidgets.QPushButton(self.centralwidget)
        self.pbtn_Cancel.setGeometry(QtCore.QRect(530, 390, 93, 28))
        self.pbtn_Cancel.setObjectName("pbtn_Cancel")
        self.pbtn_Employee_Pick = QtWidgets.QPushButton(self.centralwidget)
        self.pbtn_Employee_Pick.setGeometry(QtCore.QRect(270, 210, 21, 21))
        self.pbtn_Employee_Pick.setObjectName("pbtn_Employee_Pick")
        popup_Payment.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(popup_Payment)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 23))
        self.menubar.setObjectName("menubar")
        popup_Payment.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(popup_Payment)
        self.statusbar.setObjectName("statusbar")
        popup_Payment.setStatusBar(self.statusbar)

        self.retranslateUi(popup_Payment)
        QtCore.QMetaObject.connectSlotsByName(popup_Payment)

    def retranslateUi(self, popup_Payment):
        _translate = QtCore.QCoreApplication.translate
        popup_Payment.setWindowTitle(_translate("popup_Payment", "支款单"))
        self.lb_date.setText(_translate("popup_Payment", "支款日期"))
        self.lb_amount.setText(_translate("popup_Payment", "支款金额(含税)"))
        self.lb_department.setText(_translate("popup_Payment", "支款部门"))
        self.lb_employee.setText(_translate("popup_Payment", "支款人"))
        self.lb_note_no.setText(_translate("popup_Payment", "票据凭证号"))
        self.lb_reason.setText(_translate("popup_Payment", "支款原因"))
        self.lb_type.setText(_translate("popup_Payment", "支款方式"))
        self.pbtn_Save.setText(_translate("popup_Payment", "保存"))
        self.pbtn_Cancel.setText(_translate("popup_Payment", "取消"))
        self.pbtn_Employee_Pick.setText(_translate("popup_Payment", "☺"))
