# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frm_popup_PurchaseList_Itm_Pre.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frm_popup_PurchaseList_Itm_Pre(object):
    def setupUi(self, frm_popup_PurchaseList_Itm_Pre):
        frm_popup_PurchaseList_Itm_Pre.setObjectName("frm_popup_PurchaseList_Itm_Pre")
        frm_popup_PurchaseList_Itm_Pre.resize(940, 326)
        self.centralwidget = QtWidgets.QWidget(frm_popup_PurchaseList_Itm_Pre)
        self.centralwidget.setObjectName("centralwidget")
        self.lb_popup_PurchaseList_Itm_ProdName = QtWidgets.QLabel(self.centralwidget)
        self.lb_popup_PurchaseList_Itm_ProdName.setGeometry(QtCore.QRect(60, 50, 72, 15))
        self.lb_popup_PurchaseList_Itm_ProdName.setObjectName("lb_popup_PurchaseList_Itm_ProdName")
        self.le_popup_PurchaseList_Itm_ProdName = QtWidgets.QLineEdit(self.centralwidget)
        self.le_popup_PurchaseList_Itm_ProdName.setGeometry(QtCore.QRect(160, 50, 113, 21))
        self.le_popup_PurchaseList_Itm_ProdName.setObjectName("le_popup_PurchaseList_Itm_ProdName")
        self.le_popup_PurchaseList_Itm_ProdNum = QtWidgets.QLineEdit(self.centralwidget)
        self.le_popup_PurchaseList_Itm_ProdNum.setGeometry(QtCore.QRect(160, 100, 113, 21))
        self.le_popup_PurchaseList_Itm_ProdNum.setObjectName("le_popup_PurchaseList_Itm_ProdNum")
        self.le_popup_PurchaseList_Itm_ProdUnit = QtWidgets.QLineEdit(self.centralwidget)
        self.le_popup_PurchaseList_Itm_ProdUnit.setGeometry(QtCore.QRect(160, 150, 113, 21))
        self.le_popup_PurchaseList_Itm_ProdUnit.setObjectName("le_popup_PurchaseList_Itm_ProdUnit")
        self.lb_popup_PurchaseList_Itm_ProdNum = QtWidgets.QLabel(self.centralwidget)
        self.lb_popup_PurchaseList_Itm_ProdNum.setGeometry(QtCore.QRect(60, 100, 72, 15))
        self.lb_popup_PurchaseList_Itm_ProdNum.setObjectName("lb_popup_PurchaseList_Itm_ProdNum")
        self.lb_popup_PurchaseList_Itm_ProdUnit = QtWidgets.QLabel(self.centralwidget)
        self.lb_popup_PurchaseList_Itm_ProdUnit.setGeometry(QtCore.QRect(60, 150, 72, 15))
        self.lb_popup_PurchaseList_Itm_ProdUnit.setObjectName("lb_popup_PurchaseList_Itm_ProdUnit")
        self.pbtn_popup_PurchaseList_Itm_Pre_Cancel = QtWidgets.QPushButton(self.centralwidget)
        self.pbtn_popup_PurchaseList_Itm_Pre_Cancel.setGeometry(QtCore.QRect(790, 230, 93, 28))
        self.pbtn_popup_PurchaseList_Itm_Pre_Cancel.setObjectName("pbtn_popup_PurchaseList_Itm_Pre_Cancel")
        self.pbtn_popup_PurchaseList_Itm_Pre_Save = QtWidgets.QPushButton(self.centralwidget)
        self.pbtn_popup_PurchaseList_Itm_Pre_Save.setGeometry(QtCore.QRect(660, 230, 93, 28))
        self.pbtn_popup_PurchaseList_Itm_Pre_Save.setObjectName("pbtn_popup_PurchaseList_Itm_Pre_Save")
        self.pbtn_popup_PurchaseList_Itm_Pre_pick = QtWidgets.QPushButton(self.centralwidget)
        self.pbtn_popup_PurchaseList_Itm_Pre_pick.setGeometry(QtCore.QRect(280, 50, 31, 21))
        self.pbtn_popup_PurchaseList_Itm_Pre_pick.setObjectName("pbtn_popup_PurchaseList_Itm_Pre_pick")
        frm_popup_PurchaseList_Itm_Pre.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(frm_popup_PurchaseList_Itm_Pre)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 940, 26))
        self.menubar.setObjectName("menubar")
        frm_popup_PurchaseList_Itm_Pre.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(frm_popup_PurchaseList_Itm_Pre)
        self.statusbar.setObjectName("statusbar")
        frm_popup_PurchaseList_Itm_Pre.setStatusBar(self.statusbar)

        self.retranslateUi(frm_popup_PurchaseList_Itm_Pre)
        QtCore.QMetaObject.connectSlotsByName(frm_popup_PurchaseList_Itm_Pre)

    def retranslateUi(self, frm_popup_PurchaseList_Itm_Pre):
        _translate = QtCore.QCoreApplication.translate
        frm_popup_PurchaseList_Itm_Pre.setWindowTitle(_translate("frm_popup_PurchaseList_Itm_Pre", "采购项内容"))
        self.lb_popup_PurchaseList_Itm_ProdName.setText(_translate("frm_popup_PurchaseList_Itm_Pre", "名称"))
        self.lb_popup_PurchaseList_Itm_ProdNum.setText(_translate("frm_popup_PurchaseList_Itm_Pre", "数量"))
        self.lb_popup_PurchaseList_Itm_ProdUnit.setText(_translate("frm_popup_PurchaseList_Itm_Pre", "单位"))
        self.pbtn_popup_PurchaseList_Itm_Pre_Cancel.setText(_translate("frm_popup_PurchaseList_Itm_Pre", "取消"))
        self.pbtn_popup_PurchaseList_Itm_Pre_Save.setText(_translate("frm_popup_PurchaseList_Itm_Pre", "保存"))
        self.pbtn_popup_PurchaseList_Itm_Pre_pick.setText(_translate("frm_popup_PurchaseList_Itm_Pre", "☺"))
