# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frm_popup_Purchase_Job_Contract.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frm_popup_Purchase_Job_Contract(object):
    def setupUi(self, frm_popup_Purchase_Job_Contract):
        frm_popup_Purchase_Job_Contract.setObjectName("frm_popup_Purchase_Job_Contract")
        frm_popup_Purchase_Job_Contract.resize(626, 451)
        self.centralwidget = QtWidgets.QWidget(frm_popup_Purchase_Job_Contract)
        self.centralwidget.setObjectName("centralwidget")
        self.lb_no = QtWidgets.QLabel(self.centralwidget)
        self.lb_no.setGeometry(QtCore.QRect(60, 60, 72, 15))
        self.lb_no.setObjectName("lb_no")
        self.lb_name = QtWidgets.QLabel(self.centralwidget)
        self.lb_name.setGeometry(QtCore.QRect(330, 60, 72, 15))
        self.lb_name.setObjectName("lb_name")
        self.lb_PartyA = QtWidgets.QLabel(self.centralwidget)
        self.lb_PartyA.setGeometry(QtCore.QRect(60, 150, 72, 15))
        self.lb_PartyA.setObjectName("lb_PartyA")
        self.lb_PartyB = QtWidgets.QLabel(self.centralwidget)
        self.lb_PartyB.setGeometry(QtCore.QRect(330, 150, 72, 15))
        self.lb_PartyB.setObjectName("lb_PartyB")
        self.lb_amount = QtWidgets.QLabel(self.centralwidget)
        self.lb_amount.setGeometry(QtCore.QRect(60, 250, 72, 15))
        self.lb_amount.setObjectName("lb_amount")
        self.lb_status = QtWidgets.QLabel(self.centralwidget)
        self.lb_status.setGeometry(QtCore.QRect(330, 250, 72, 15))
        self.lb_status.setObjectName("lb_status")
        self.le_no = QtWidgets.QLineEdit(self.centralwidget)
        self.le_no.setGeometry(QtCore.QRect(160, 60, 113, 21))
        self.le_no.setObjectName("le_no")
        self.le_PartyA = QtWidgets.QLineEdit(self.centralwidget)
        self.le_PartyA.setGeometry(QtCore.QRect(160, 150, 113, 21))
        self.le_PartyA.setObjectName("le_PartyA")
        self.le_amount = QtWidgets.QLineEdit(self.centralwidget)
        self.le_amount.setGeometry(QtCore.QRect(160, 250, 113, 21))
        self.le_amount.setObjectName("le_amount")
        self.le_name = QtWidgets.QLineEdit(self.centralwidget)
        self.le_name.setGeometry(QtCore.QRect(440, 60, 113, 21))
        self.le_name.setObjectName("le_name")
        self.le_PartyB = QtWidgets.QLineEdit(self.centralwidget)
        self.le_PartyB.setGeometry(QtCore.QRect(440, 150, 113, 21))
        self.le_PartyB.setObjectName("le_PartyB")
        self.le_status = QtWidgets.QLineEdit(self.centralwidget)
        self.le_status.setGeometry(QtCore.QRect(440, 250, 113, 21))
        self.le_status.setObjectName("le_status")
        self.pbtn_Cancel = QtWidgets.QPushButton(self.centralwidget)
        self.pbtn_Cancel.setGeometry(QtCore.QRect(470, 360, 93, 28))
        self.pbtn_Cancel.setObjectName("pbtn_Cancel")
        self.pbtn_Save = QtWidgets.QPushButton(self.centralwidget)
        self.pbtn_Save.setGeometry(QtCore.QRect(340, 360, 93, 28))
        self.pbtn_Save.setObjectName("pbtn_Save")
        self.pbtn_PartyA_Pick = QtWidgets.QPushButton(self.centralwidget)
        self.pbtn_PartyA_Pick.setGeometry(QtCore.QRect(280, 150, 21, 21))
        self.pbtn_PartyA_Pick.setObjectName("pbtn_PartyA_Pick")
        self.pbtn_PartyB_Pick = QtWidgets.QPushButton(self.centralwidget)
        self.pbtn_PartyB_Pick.setGeometry(QtCore.QRect(560, 150, 21, 21))
        self.pbtn_PartyB_Pick.setObjectName("pbtn_PartyB_Pick")
        frm_popup_Purchase_Job_Contract.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(frm_popup_Purchase_Job_Contract)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 626, 23))
        self.menubar.setObjectName("menubar")
        frm_popup_Purchase_Job_Contract.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(frm_popup_Purchase_Job_Contract)
        self.statusbar.setObjectName("statusbar")
        frm_popup_Purchase_Job_Contract.setStatusBar(self.statusbar)

        self.retranslateUi(frm_popup_Purchase_Job_Contract)
        QtCore.QMetaObject.connectSlotsByName(frm_popup_Purchase_Job_Contract)

    def retranslateUi(self, frm_popup_Purchase_Job_Contract):
        _translate = QtCore.QCoreApplication.translate
        frm_popup_Purchase_Job_Contract.setWindowTitle(_translate("frm_popup_Purchase_Job_Contract", "合同"))
        self.lb_no.setText(_translate("frm_popup_Purchase_Job_Contract", "合同编号"))
        self.lb_name.setText(_translate("frm_popup_Purchase_Job_Contract", "合同名称"))
        self.lb_PartyA.setText(_translate("frm_popup_Purchase_Job_Contract", "甲方客户"))
        self.lb_PartyB.setText(_translate("frm_popup_Purchase_Job_Contract", "乙方客户"))
        self.lb_amount.setText(_translate("frm_popup_Purchase_Job_Contract", "合同金额"))
        self.lb_status.setText(_translate("frm_popup_Purchase_Job_Contract", "合同状态"))
        self.pbtn_Cancel.setText(_translate("frm_popup_Purchase_Job_Contract", "取消"))
        self.pbtn_Save.setText(_translate("frm_popup_Purchase_Job_Contract", "保存"))
        self.pbtn_PartyA_Pick.setText(_translate("frm_popup_Purchase_Job_Contract", "☺"))
        self.pbtn_PartyB_Pick.setText(_translate("frm_popup_Purchase_Job_Contract", "☺"))
