# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frm_popup_Purchase_Inquiry.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frm_popup_Purchase_Inquiry(object):
    def setupUi(self, frm_popup_Purchase_Inquiry):
        frm_popup_Purchase_Inquiry.setObjectName("frm_popup_Purchase_Inquiry")
        frm_popup_Purchase_Inquiry.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(frm_popup_Purchase_Inquiry)
        self.centralwidget.setObjectName("centralwidget")
        self.pbtn_Cancel = QtWidgets.QPushButton(self.centralwidget)
        self.pbtn_Cancel.setGeometry(QtCore.QRect(520, 380, 93, 28))
        self.pbtn_Cancel.setObjectName("pbtn_Cancel")
        self.pbtn_Save = QtWidgets.QPushButton(self.centralwidget)
        self.pbtn_Save.setGeometry(QtCore.QRect(390, 380, 93, 28))
        self.pbtn_Save.setObjectName("pbtn_Save")
        self.lb_num = QtWidgets.QLabel(self.centralwidget)
        self.lb_num.setGeometry(QtCore.QRect(90, 60, 51, 16))
        self.lb_num.setObjectName("lb_num")
        self.lb_price = QtWidgets.QLabel(self.centralwidget)
        self.lb_price.setGeometry(QtCore.QRect(90, 100, 51, 16))
        self.lb_price.setObjectName("lb_price")
        self.lb_cycle = QtWidgets.QLabel(self.centralwidget)
        self.lb_cycle.setGeometry(QtCore.QRect(90, 140, 61, 16))
        self.lb_cycle.setObjectName("lb_cycle")
        self.le_num = QtWidgets.QLineEdit(self.centralwidget)
        self.le_num.setGeometry(QtCore.QRect(170, 60, 113, 20))
        self.le_num.setObjectName("le_num")
        self.le_price = QtWidgets.QLineEdit(self.centralwidget)
        self.le_price.setGeometry(QtCore.QRect(170, 100, 113, 20))
        self.le_price.setObjectName("le_price")
        self.le_cycle = QtWidgets.QLineEdit(self.centralwidget)
        self.le_cycle.setGeometry(QtCore.QRect(170, 140, 113, 20))
        self.le_cycle.setObjectName("le_cycle")
        self.te_Comments = QtWidgets.QTextEdit(self.centralwidget)
        self.te_Comments.setGeometry(QtCore.QRect(170, 190, 381, 111))
        self.te_Comments.setObjectName("te_Comments")
        self.lb_Comments = QtWidgets.QLabel(self.centralwidget)
        self.lb_Comments.setGeometry(QtCore.QRect(90, 190, 72, 15))
        self.lb_Comments.setObjectName("lb_Comments")
        frm_popup_Purchase_Inquiry.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(frm_popup_Purchase_Inquiry)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 23))
        self.menubar.setObjectName("menubar")
        frm_popup_Purchase_Inquiry.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(frm_popup_Purchase_Inquiry)
        self.statusbar.setObjectName("statusbar")
        frm_popup_Purchase_Inquiry.setStatusBar(self.statusbar)

        self.retranslateUi(frm_popup_Purchase_Inquiry)
        QtCore.QMetaObject.connectSlotsByName(frm_popup_Purchase_Inquiry)

    def retranslateUi(self, frm_popup_Purchase_Inquiry):
        _translate = QtCore.QCoreApplication.translate
        frm_popup_Purchase_Inquiry.setWindowTitle(_translate("frm_popup_Purchase_Inquiry", "询价"))
        self.pbtn_Cancel.setText(_translate("frm_popup_Purchase_Inquiry", "取消"))
        self.pbtn_Save.setText(_translate("frm_popup_Purchase_Inquiry", "保存"))
        self.lb_num.setText(_translate("frm_popup_Purchase_Inquiry", "数量"))
        self.lb_price.setText(_translate("frm_popup_Purchase_Inquiry", "总价"))
        self.lb_cycle.setText(_translate("frm_popup_Purchase_Inquiry", "供货周期"))
        self.lb_Comments.setText(_translate("frm_popup_Purchase_Inquiry", "备注"))
