# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frm_popup_Purchase_Job.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_popup_Purchase_Job(object):
    def setupUi(self, popup_Purchase_Job):
        popup_Purchase_Job.setObjectName("popup_Purchase_Job")
        popup_Purchase_Job.resize(594, 371)
        self.centralwidget = QtWidgets.QWidget(popup_Purchase_Job)
        self.centralwidget.setObjectName("centralwidget")
        self.lEdit_Purchase_Job_No = QtWidgets.QLineEdit(self.centralwidget)
        self.lEdit_Purchase_Job_No.setGeometry(QtCore.QRect(100, 60, 113, 20))
        self.lEdit_Purchase_Job_No.setObjectName("lEdit_Purchase_Job_No")
        self.lEdit_Purchase_Job_Supppiler = QtWidgets.QLineEdit(self.centralwidget)
        self.lEdit_Purchase_Job_Supppiler.setGeometry(QtCore.QRect(100, 110, 113, 20))
        self.lEdit_Purchase_Job_Supppiler.setObjectName("lEdit_Purchase_Job_Supppiler")
        self.lEdit_Purchase_Job_Status = QtWidgets.QLineEdit(self.centralwidget)
        self.lEdit_Purchase_Job_Status.setGeometry(QtCore.QRect(100, 150, 113, 20))
        self.lEdit_Purchase_Job_Status.setObjectName("lEdit_Purchase_Job_Status")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 60, 54, 12))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 71, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 150, 61, 21))
        self.label_4.setObjectName("label_4")
        self.pbtn_Purchase_Job_Save = QtWidgets.QPushButton(self.centralwidget)
        self.pbtn_Purchase_Job_Save.setGeometry(QtCore.QRect(330, 270, 75, 23))
        self.pbtn_Purchase_Job_Save.setObjectName("pbtn_Purchase_Job_Save")
        self.pbtn_Purchase_Job_Cancel = QtWidgets.QPushButton(self.centralwidget)
        self.pbtn_Purchase_Job_Cancel.setGeometry(QtCore.QRect(440, 270, 75, 23))
        self.pbtn_Purchase_Job_Cancel.setObjectName("pbtn_Purchase_Job_Cancel")
        self.pbtn_Purchase_Job_Pick = QtWidgets.QPushButton(self.centralwidget)
        self.pbtn_Purchase_Job_Pick.setGeometry(QtCore.QRect(220, 110, 21, 21))
        self.pbtn_Purchase_Job_Pick.setObjectName("pbtn_Purchase_Job_Pick")
        popup_Purchase_Job.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(popup_Purchase_Job)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 594, 23))
        self.menubar.setObjectName("menubar")
        popup_Purchase_Job.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(popup_Purchase_Job)
        self.statusbar.setObjectName("statusbar")
        popup_Purchase_Job.setStatusBar(self.statusbar)

        self.retranslateUi(popup_Purchase_Job)
        QtCore.QMetaObject.connectSlotsByName(popup_Purchase_Job)

    def retranslateUi(self, popup_Purchase_Job):
        _translate = QtCore.QCoreApplication.translate
        popup_Purchase_Job.setWindowTitle(_translate("popup_Purchase_Job", "MainWindow"))
        self.label.setText(_translate("popup_Purchase_Job", "采购编号"))
        self.label_3.setText(_translate("popup_Purchase_Job", "供应商"))
        self.label_4.setText(_translate("popup_Purchase_Job", "状态"))
        self.pbtn_Purchase_Job_Save.setText(_translate("popup_Purchase_Job", "保存"))
        self.pbtn_Purchase_Job_Cancel.setText(_translate("popup_Purchase_Job", "取消"))
        self.pbtn_Purchase_Job_Pick.setText(_translate("popup_Purchase_Job", "☺"))
